Tracker44/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('core/', include('core.urls')),
    path('user_profile/', include('user_profile.urls')),
    path('scenarios/', include('scenarios.urls')),
    path('admin/', admin.site.urls)
]

core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # /core/
    path('', views.index, name='index'),
]

scenarios/urls.py
from django.urls import path

import scenarios.views


app_name = 'scenarios'

urlpatterns = [
    # /scenarios/
    path('', scenarios.views.expansion_list, name='expansions'),
    # /scenarios/M44/
    # /scenarios/all/
    path('<expansion_abbreviation>/', scenarios.views.expansion_scenarios, name='expansion_scenarios')
]

user_profile/urls.py
from django.urls import path

import user_profile.views


app_name = 'user_profile'

urlpatterns = [
    # /user_profile/sign_up
    path('sign_up/', user_profile.views.sign_up, name="sign_up"),
    # /user_profile/logout
    path('logout/', user_profile.views.logout_user, name="logout"),
    # /user_profile/login
    path('login/', user_profile.views.login_user, name="login"),
    # /user_profile/change_password
    path('change_password/', user_profile.views.change_password, name="change_password"),
    # /user_profile/profile
    path('profile/', user_profile.views.profile, name="profile"),
    # /user_profile/log_play
    path('log_play/', user_profile.views.log_play, name="log_play")
]

core/models.py
from django.db import models

# Create your models here.

scenarios/models.py
from django.db import models


class ExpansionManager(models.Manager):
    def get_by_natural_key(self, abbreviation):
        return self.get(abbreviation=abbreviation)


class SubExpansionManager(models.Manager):
    def get_by_natural_key(self, abbreviation):
        return self.get(abbreviation=abbreviation)


class Expansion(models.Model):
    name = models.CharField(max_length=50)
    abbreviation = models.CharField(max_length=25, unique=True)

    objects = ExpansionManager()


class SubExpansion(models.Model):
    name = models.CharField(max_length=50)
    abbreviation = models.CharField(max_length=25, unique=True)
    parent = models.ForeignKey(Expansion, on_delete=models.CASCADE)

    objects = SubExpansionManager()


class Scenario(models.Model):
    name = models.CharField(max_length=50)
    expansion = models.ForeignKey(Expansion, on_delete=models.CASCADE)
    sub_expansion = models.ForeignKey(SubExpansion, on_delete=models.CASCADE, blank=True, null=True)
    number = models.CharField(max_length=15)
    date = models.CharField(max_length=25)

    class BoardTypes(models.IntegerChoices):
        COUNTRYSIDE = 1
        WINTER = 2
        DESERT = 3
        BEACH = 4

    board = models.IntegerField(choices=BoardTypes.choices)

    class ScenarioTypes(models.IntegerChoices):
        STANDARD = 1
        OVERLORD = 2
        BREAKTHROUGH = 3
        BREAKLORD = 4

    scenario_type = models.IntegerField(choices=ScenarioTypes.choices)

user_profile/models.py
from django.db import models
from scenarios.models import Scenario, Expansion
from django.contrib.auth.models import User
from django.utils import timezone

from datetime import timedelta


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    scenarios_played = models.IntegerField(default=0)

    def get_num_scenarios_last_week(self):
        one_week_ago = timezone.now().date() - timedelta(days=7)
        tommorow = timezone.now().date() + timedelta(days=7)
        # Use tomorrow because the bound is "0am on the given date"
        return len(self.loggedplay_set.filter(date__range=(one_week_ago, tommorow)))

    def get_num_scenarios_this_month(self):
        return len(self.loggedplay_set.filter(date__month=timezone.now().month))

    def get_num_scenarios_this_year(self):
        return len(self.loggedplay_set.filter(date__month=timezone.now().year))

    def get_list_expansions_completed(self):
        expansions_completed = []
        for expansion in Expansion.objects.all():
            # Check if the number of scenarios the user has played for an expansion equals the total scenarios for
            # that expansion
            if len(self.loggedplay_set.filter(scenario__expansion=expansion)) == len(expansion.scenario_set.all()):
                expansions_completed.append(expansion)
        return expansions_completed

    def get_list_expansions_uncompleted(self):
        expansions_uncompleted = []
        for expansion in Expansion.objects.all():
            expansion_plays = len(self.loggedplay_set.filter(scenario__expansion=expansion))
            expansion_scenarios = len(expansion.scenario_set.all())
            if expansion_plays != expansion_scenarios:
                expansions_uncompleted.append(expansion.name + " (" + str(expansion_plays) + "/" + str(expansion_scenarios) + ")")
        return expansions_uncompleted


class LoggedPlay(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    scenario = models.ForeignKey(Scenario, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)

user_profile/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['password1'].help_text = "Must be at least 8 characters"
        self.fields['password2'].help_text = "Confirm Password"
        self.fields['username'].help_text = None

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'core/index.html')

scenarios/views.py
from django.shortcuts import render, get_object_or_404

from .models import Scenario, Expansion


def expansion_list(request):
    return render(request, 'scenarios/expansion_list.html')


def expansion_scenarios(request, expansion_abbreviation):
    if expansion_abbreviation == 'all':
        context = {'scenarios': Scenario.objects.all(), 'title': 'ALL SCENARIOS'}
    else:
        expansion = get_object_or_404(Expansion, abbreviation=expansion_abbreviation)
        context = {'scenarios': expansion.scenario_set.all(), 'title': expansion.name.upper()}
    return render(request, 'scenarios/scenario_list.html', context)

user_profile/views.py
from django.contrib.auth import login, logout, authenticate, update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.shortcuts import render, redirect

from user_profile.forms import SignUpForm
from user_profile.models import UserProfile


def sign_up(request):
    context = {}
    form = SignUpForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            user = form.save()
            user_profile = UserProfile(user=user)
            user_profile.save()
            login(request, user)
            return redirect('index')
    context['form'] = form
    return render(request, 'registration/sign_up.html', context)


def logout_user(request):
    logout(request)
    return redirect("index")


def login_user(request):
    if request.method == "POST":
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('index')

    context = {}
    form = AuthenticationForm()
    context['form'] = form
    return render(request, "registration/login.html", context)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('index')
    else:
        context = {}
        form = PasswordChangeForm(user=request.user)
        context['form'] = form
        return render(request, "registration/password_change.html", context)


def profile(request):
    if not request.user.is_authenticated:
        return redirect('user_profile:login')
    else:
        return render(request, "profile.html", {'profile': UserProfile.objects.get(user=request.user)})


def log_play(request):
    if not request.user.is_authenticated:
        return redirect('user_profile:login')
    else:
        return render(request, "play_entry.html")

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{%  static 'core/css/style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sora">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tracker 44</title>
</head>
<body style="font-family: 'Sora', serif;">

    <header>
        <h1 style="grid-column-start: 2;">TRACKER '44</h1>

        {% if user.is_authenticated %}
        <div class="user_auth">
            <a href="{% url 'user_profile:profile' %}">{{ user.username }}</a><br>
            <a href={% url 'user_profile:logout' %}>Logout</a>
        </div>

        {% else %}
            <div class="user_auth">
                <a href={% url 'user_profile:login' %}>Login</a><br>
                <a href={% url 'user_profile:sign_up' %}>Register</a>
            </div>

        {% endif %}

    </header>

    {% block content %}
    {% endblock %}

</body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}

    <div class="nav_images">
        <div>
            <a href="{% url 'scenarios:expansions' %}"><img class="nav_icon" src="{%  static 'core/images/hex_icon.png' %}"></a>
            <p>SCENARIOS</p>
        </div>
        <div>
            <a href="{% url 'user_profile:log_play' %}"><img class="nav_icon" src="{%  static 'core/images/dice_icon.png' %}"></a>
            <p>LOG A PLAY</p>
        </div>
        <div>
            <a href="{% url 'user_profile:profile' %}"><img class="nav_icon" src="{%  static 'core/images/stars_icon.png' %}"></a>
            <p>PROFILE</p>
        </div>
    </div>

{% endblock %}

scenarios/templates/scenarios/all_scenarios.html
<!doctype html>
<html lang="en">
  <head>
      {% load static %}
      <link rel="stylesheet" type="text/css" href=http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css>
      <link rel="stylesheet" type="text/css" href=http://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css>
      <link rel="stylesheet" type="text/css" href="{%  static 'core/style.css' %}">
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sora">
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Tracker '44</title>
  </head>
  <body>
    <header>
        <h1 style="grid-column-start: 2;">TRACKER '44</h1>

        {% if user.is_authenticated %}
            <div class="user_auth">
              <a href="https://www.w3schools.com/howto/howto_css_image_overlay.asp">{{ user.username }}</a><br>
              <a href={% url 'user_profile:logout' %}>Logout</a>
            </div>

        {% else %}
            <div class="user_auth">
                <a href={% url 'user_profile:login' %}>Login</a><br>
                <a href={% url 'user_profile:sign_up' %}>Register</a>
            </div>

        {% endif %}

    </header>

    <br>

    <div class="table-responsive">
        <table id="example" class="table table-striped table-bordered">
            <thead class="thead-dark">
            <tr>
                <th>Scenario</th>
                <th>Expansion</th>
                <th style="text-align: center">Board</th>
                <th>Date</th>
                <th>Number</th>
            </tr>
            </thead>
        <tbody>
        {% for scenario in scenarios %}
            {% if scenario.get_scenario_type_display == 'Overlord' %}
            <tr class="table-danger">
            {% elif scenario.get_scenario_type_display == 'Breaktrough'%}
            <tr class="table-warning">
            {% elif scenario.get_scenario_type_display == 'Breaklord'%}
            <tr class="table-info">
            {% else %}
            <tr>
            {% endif %}

                <td>{{  scenario.name }} </td>
                {% if scenario.sub_expansion %}
                    <td>{{ scenario.expansion.name }} - {{ scenario.sub_expansion.name }} </td>
                {% else %}
                    <td>{{ scenario.expansion.name }}</td>
                {% endif %}
                {% if scenario.get_board_display == 'Countryside' %}
                    <td style="text-align: center"><img src="{% static 'core/images/green_hex_icon_small.png' %}"></td>
                {% elif scenario.get_board_display == 'Winter' %}
                    <td style="text-align: center"><img src="{% static 'core/images/white_hex_icon_small.png' %}"></td>
                {% elif scenario.get_board_display == 'Desert' %}
                    <td style="text-align: center"><img src="{% static 'core/images/brown_hex_icon_small.png' %}"></td>
                {% elif scenario.get_board_display == 'Beach' %}
                    <td style="text-align: center"><img src="{% static 'core/images/beach_hex_icon_small.png' %}"></td>
                {% endif %}
                <td>{{ scenario.date }}</td>
                <td>{{ scenario.number }}</td>
            </tr>
        {% endfor%}
        </tbody>
    </table>
    </div>

    <script type="text/javascript" charset="utf8" src= "http://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript" charset="utf8" src=http://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js></script>
    <script type="text/javascript" charset="utf8" src=http://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js></script>
    <script type="text/javascript" src="{% static 'core/js/initialize_data_tables.js' %}"></script>
  </body>
</html>

scenarios/templates/scenarios/expansion_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
    {% load static %}
    <div class = "expansion_grid">
        <div class="expansion" >

            <a href="{% url 'scenarios:expansion_scenarios' 'all' %}"> ALL </a>
        </div>
        <div class="expansion">
            <a href="{% url 'scenarios:expansion_scenarios' 'M44' %}" style="color: darkgreen"> M44 </a>
        </div>
        <div class="expansion">
            <a href="{% url 'scenarios:expansion_scenarios' 'AIR' %}" style="color: lightskyblue"> AIR </a>
        </div>

        <div class="expansion">
            <a href="{% url 'scenarios:expansion_scenarios' 'MT' %}" style="color: tan"> MT </a>
        </div>
        <div class="expansion">
            <a href="{% url 'scenarios:expansion_scenarios' 'PT' %}" style="color: dodgerblue"> PT </a>
        </div>
        <div class="expansion">
            <a href="{% url 'scenarios:expansion_scenarios' 'EF' %}" style="color: darkred"> EF </a>
        </div>

        <div class="expansion">
            <a href="{% url 'scenarios:expansion_scenarios' 'TP' %}" style="color: lightgreen"> TP </a>
        </div>
        <div class="expansion">
            <a href="{% url 'scenarios:expansion_scenarios' 'WW' %}" style="color: cornflowerblue" > WW </a>
        </div>
        <div class="expansion">
            <a href="{% url 'scenarios:expansion_scenarios' 'EP' %}" style="color: darkgrey"> EP </a>
        </div>

        <div class="expansion">
            <a href="{% url 'scenarios:expansion_scenarios' 'DDL' %}" style="color: darkgreen"> DDL </a>
        </div>
        <div class="expansion">
            <a href="{% url 'scenarios:expansion_scenarios' 'BT' %}" style="color: darkorange"> BT </a>
        </div>
        <div class="expansion">
            <a href="{% url 'scenarios:expansion_scenarios' 'NFP' %}" style="color: mediumpurple" > NFP </a>
        </div>

        <div class="expansion">
            <a href="{% url 'scenarios:expansion_scenarios' 'CB1' %}"> CB 1 </a>
        </div>
        <div class="expansion">
            <a href="{% url 'scenarios:expansion_scenarios' 'CB2' %}"> CB 2 </a>
        </div>
        <div class="expansion">
            <a href="{% url 'scenarios:expansion_scenarios' 'PC' %}" style="font-size: 40px;"> CAMPAIGN <br> PROMOS </a>
        </div>

        <div class="expansion">
            <a href="{% url 'scenarios:expansion_scenarios' 'BM1' %}" style="font-size: 40px;"> BATTLE<br> MAPS <br> SERIES 1 </a>
        </div>
        <div class="expansion">
            <a href="{% url 'scenarios:expansion_scenarios' 'BM2' %}" style="font-size: 40px;"> BATTLE<br> MAPS <br> SERIES 2 </a>
        </div>
        <div class="expansion">
            <a href="{% url 'scenarios:expansion_scenarios' 'OP' %}" style="font-size: 45px;"> OTHER <br> PROMOS </a>
        </div>

        <div class="expansion">
            <a href="{% url 'scenarios:expansion_scenarios' 'FO' %}" style="font-size: 45px;"> FRENCH <br> OPEN </a>
        </div>
        <div class="expansion">
            <a href="{% url 'scenarios:expansion_scenarios' 'DO' %}" style="font-size: 45px;"> DUTCH <br> OPEN </a>
        </div>
        <div class="expansion">
            <a href="{% url 'scenarios:expansion_scenarios' 'O' %}" style="font-size: 60px;"> OTHER  </a>
        </div>
    </div>

{% endblock %}

scenarios/templates/scenarios/scenario_list.html
<!doctype html>
<html lang="en">
  <head>
      {% load static %}
      <link rel="stylesheet" type="text/css" href=http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css>
      <link rel="stylesheet" type="text/css" href=http://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css>
      <link rel="stylesheet" type="text/css" href="{%  static 'core/css/style.css' %}">
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sora">
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Tracker '44</title>
  </head>
  <body>
    <header>
        <h1 style="grid-column-start: 2;">TRACKER '44</h1>

        {% if user.is_authenticated %}
            <div class="user_auth">
              <a href="{% url 'user_profile:profile' %}">{{ user.username }}</a><br>
              <a href={% url 'user_profile:logout' %}>Logout</a>
            </div>

        {% else %}
            <div class="user_auth">
                <a href={% url 'user_profile:login' %}>Login</a><br>
                <a href={% url 'user_profile:sign_up' %}>Register</a>
            </div>

        {% endif %}

    </header>

    <br>

    <h2>{{ title }}</h2>

    <div class="table-responsive">
        <table id="example" class="table table-striped table-bordered">
            <thead class="thead-dark">
            <tr>
                <th>Scenario</th>
                <th>Expansion</th>
                <th style="text-align: center">Board</th>
                <th>Date</th>
                <th>Number</th>
            </tr>
            </thead>
        <tbody>
        {% for scenario in scenarios %}
            {% if scenario.get_scenario_type_display == 'Overlord' %}
            <tr class="table-danger">
            {% elif scenario.get_scenario_type_display == 'Breaktrough'%}
            <tr class="table-warning">
            {% elif scenario.get_scenario_type_display == 'Breaklord'%}
            <tr class="table-info">
            {% else %}
            <tr>
            {% endif %}

                <td>{{  scenario.name }} </td>
                {% if scenario.sub_expansion %}
                    <td>{{ scenario.expansion.name }} - {{ scenario.sub_expansion.name }} </td>
                {% else %}
                    <td>{{ scenario.expansion.name }}</td>
                {% endif %}
                {% if scenario.get_board_display == 'Countryside' %}
                    <td style="text-align: center"><img src="{% static 'core/images/green_hex_icon_small.png' %}"></td>
                {% elif scenario.get_board_display == 'Winter' %}
                    <td style="text-align: center"><img src="{% static 'core/images/white_hex_icon_small.png' %}"></td>
                {% elif scenario.get_board_display == 'Desert' %}
                    <td style="text-align: center"><img src="{% static 'core/images/brown_hex_icon_small.png' %}"></td>
                {% elif scenario.get_board_display == 'Beach' %}
                    <td style="text-align: center"><img src="{% static 'core/images/beach_hex_icon_small.png' %}"></td>
                {% endif %}
                <td>{{ scenario.date }}</td>
                <td>{{ scenario.number }}</td>
            </tr>
        {% endfor%}
        </tbody>
    </table>
    </div>

    <script type="text/javascript" charset="utf8" src= "http://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript" charset="utf8" src=http://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js></script>
    <script type="text/javascript" charset="utf8" src=http://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js></script>
    <script type="text/javascript" src="{% static 'core/js/initialize_data_tables.js' %}"></script>
  </body>
</html>

user_profile/templates/auth_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{%  static 'core/css/style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sora">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tracker 44</title>
</head>
<body style="font-family: 'Sora', serif; text-align: center;">

    <header>
        <h1 style="grid-column-start: 2;">TRACKER '44</h1>
    </header>

    {% block content %}
    {% endblock %}

</body>
</html>

user_profile/templates/play_entry.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
    <h2>ENTER A PLAY</h2>
{% endblock %}

user_profile/templates/profile.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<div style="text-align: center">

    <p class="profile_big_text"> Scenarios Played </p>
    <hr style="width:200px">
    <p class="profile_big_text">{{ profile.scenarios_played }} / 640 </p><br>

    <p>Scenarios Played Last Week</p>
    <p>{{ profile.get_num_scenarios_last_week }}</p>
    <p>Scenarios Played This Month</p>
    <p>{{ profile.get_num_scenarios_this_month }}</p>
    <p>Scenarios Played This Year</p>
    <p>{{ profile.get_num_scenarios_this_year }}</p><br>

    <p class="profile_big_text">Completed Expansions</p>
    <hr style="width:300px">
    {% if profile.get_list_expansions_completed %}
        {% for expansion in profile.get_list_expansions_completed %}
            <p>{{ expansion.name }}</p>
        {% endfor %}
    {% else %}
        <p>No expansions completed yet!</p>
    {% endif %}

    <p class="profile_big_text">Uncompleted Expansions</p>
    <hr style="width:300px">
    {% for expansion in profile.get_list_expansions_uncompleted %}
        <p>{{ expansion }}</p>
    {% endfor %}

    <br><br>

    <a class="profile_big_text" href="{% url 'user_profile:change_password' %}" style="text-decoration: underline; color: #444">Change Password</a><br><br>
</div>
{% endblock %}